version: '3'
services:
  camel:
    build: .
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - JAVA_OPTS=-DBROKER_URL=tcp://activemq:61616
  activemq:
    image: "rmohr/activemq:5.15.6-alpine"
    ports:
     - "8161:8161"
     - "61616:61616"